apiVersion: v1
kind: Secret
metadata:
  name: dw-awx-admin-password
  namespace: awx
stringData:
  password: admin
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: dw-awx
spec:
  service_type: nodeport
