version: "3.7"

services:
  user:
    image: 862167864120.dkr.ecr.us-east-1.amazonaws.com/dw-user-microservice:01348ed
    env_file:
      - .env
    environment:
      - APP_PORT=${USER_PORT}
    ports:
      - ${USER_PORT}:${USER_PORT}

  bank:
    image: 862167864120.dkr.ecr.us-east-1.amazonaws.com/dw-bank-microservice:ae84f31
    env_file:
      - .env
    environment:
      - APP_PORT=${BANK_PORT}
    ports:
      - ${BANK_PORT}:${BANK_PORT}

  transaction:
    image: 862167864120.dkr.ecr.us-east-1.amazonaws.com/dw-transaction-microservice:054e2a0
    env_file:
      - .env
    environment:
      - APP_PORT=${TRANSACTION_PORT}
    ports:
      - ${TRANSACTION_PORT}:${TRANSACTION_PORT}

  underwriter:
    image: 862167864120.dkr.ecr.us-east-1.amazonaws.com/dw-underwriter-microservice:baad1dc
    env_file:
      - .env
    environment:
      - APP_PORT=${UNDERWRITER_PORT}
    ports:
      - ${UNDERWRITER_PORT}:${UNDERWRITER_PORT}
