version: "3.7"

services:
  user:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/dw-user-microservice:latest
    env_file:
      - .env
    environment:
      - APP_PORT=${USER_PORT}
    ports:
      - ${USER_PORT}:${USER_PORT}
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G

  bank:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/dw-bank-microservice:latest
    env_file:
      - .env
    environment:
      - APP_PORT=${BANK_PORT}
    ports:
      - ${BANK_PORT}:${BANK_PORT}
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G

  transaction:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/dw-transaction-microservice:latest
    env_file:
      - .env
    environment:
      - APP_PORT=${TRANSACTION_PORT}
    ports:
      - ${TRANSACTION_PORT}:${TRANSACTION_PORT}
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G

  underwriter:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/dw-underwriter-microservice:latest
    env_file:
      - .env
    environment:
      - APP_PORT=${UNDERWRITER_PORT}
    ports:
      - ${UNDERWRITER_PORT}:${UNDERWRITER_PORT}
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
