version: "3.7"

volumes:
  aline-mysql-data-local:

networks:
  default:
    name: aline-network-local

services:
  alinedb-local:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: alinedb-local
    expose:
      - 3306
    env_file:
      - .env
    volumes:
      - ./init-sql:/docker-entrypoint-initdb.d:ro
      - aline-mysql-data-local:/var/lib/mysql
    cap_add:
      - SYS_NICE

  adminer:
    image: adminer
    container_name: aline-adminer
    ports:
      - 9000:8080
    depends_on:
      - alinedb-local

  user:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/dw-user-microservice:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - APP_PORT=8070
    ports:
      - 8070:8070
    depends_on:
      - alinedb-local

  bank:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/dw-bank-microservice:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - APP_PORT=8083
    ports:
      - 8083:8083
    depends_on:
      - alinedb-local

  transaction:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/dw-transaction-microservice:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - APP_PORT=8073
    ports:
      - 8073:8073
    depends_on:
      - alinedb-local

  underwriter:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/dw-underwriter-microservice:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - APP_PORT=8071
    ports:
      - 8071:8071
    depends_on:
      - alinedb-local
