- name: Configure bastion
  hosts: bastion
  become_user: ubuntu
  remote_user: ubuntu
  tasks:
    - name: Set vim as default editor
      shell: echo "EDITOR=vim" >> .bashrc

    - name: Update apt repo
      command: sudo apt update

    - name: Update packages
      command: sudo apt upgrade -y

    - name: Install git
      command: sudo apt install -y git

    - name: Install mysql client
      command: sudo apt install -y mysql-client-core-8.0

    - name: Install JQ
      command: sudo apt install -y jq

    - name: Install unzip
      command: sudo apt install -y unzip

    - name: Install AWS CLI
      command: sudo apt install awscli -y

    - name: Install make
      command: sudo apt install make -y

    - name: Install eksctl
      shell: |
        curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin

    - name: Install Kubectl
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
