- name: Init EKS Cluster
  hosts: bastion
  become: yes
  remote_user: ubuntu
  vars:
    ansible_ssh_private_key_file: ../files/dw-us-east-1.pem
  tasks:
    - name: Copy Repo
      command: git clone

    - name: Init
      command: make init
