- name: Init EKS Cluster
  hosts: bastion
  become_user: ubuntu
  remote_user: ubuntu
  vars:
    aws_environment:
      AWS_ACCESS_KEY_ID: "{{aws_key}}"
      AWS_SECRET_ACCESS_KEY: "{{aws_secret}}"
      AWS_DEFAULT_REGION: "{{aws_region}}"
    branch: "{{ branch | default('main')}}"

  tasks:
    - name: Copy Repo
      shell:
        cmd: rm -rf devops; git clone {{ git_repo }} devops
        chdir: ~

    - name: Checkout branch
      shell:
        cmd: git checkout {{ branch }}
        chdir: ~/devops

    - name: Get makefile env
      environment: "{{aws_environment}}"
      shell:
        cmd: aws s3api get-object --bucket {{s3_bucket}} --key env/.eksctl.env  .env
        chdir: ~/devops/eksctl

    - name: Add policies
      environment: "{{aws_environment}}"
      ignore_errors: yes
      shell:
        cmd: make create_policies
        chdir: ~/devops/eksctl

    - name: Init cluster
      environment: "{{aws_environment}}"
      shell:
        cmd: make init
        chdir: ~/devops/eksctl
