- name: Init EKS Cluster
  hosts: bastion
  become_user: ubuntu
  remote_user: ubuntu
  tasks:
    - name: Copy Repo
      shell:
        chdir: ~
        cmd: rm -rf devops; git clone {{ git_repo }} devops

    - name: Checkout branch
      shell:
        chdir: ~/devops
        cmd: git checkout {{ branch }}

    - name: Get makefile env
      environment: "{{ aws_environment }}"
      shell:
        chdir: ~/devops/eksctl
        cmd: aws s3api get-object --bucket {{s3_bucket}} --key env/.eksctl.env  .env

    - name: Add policies
      environment: "{{ aws_environment }}"
      ignore_errors: yes
      shell:
        chdir: ~/devops/eksctl
        cmd: make create_policies

    - name: Init cluster
      environment: "{{ aws_environment }}"
      shell:
        chdir: ~/devops/eksctl
        cmd: make init

    - name: Install services
      shell:
        chdir: ~/devops/kubernetes/eks
        cmd: make init
