- name: Copy Repo
  shell:
    chdir: /tmp
    cmd: rm -rf devops; git clone -b {{ branch }} {{ git_repo }} devops

- name: Get eksctl makefile env
  shell:
    chdir: /tmp/devops/eksctl
    cmd: aws s3api get-object --bucket {{s3_bucket}} --key env/.eksctl.env  .env

- name: Init cluster
  shell:
    chdir: /tmp/devops/eksctl
    cmd: make init

- name: Set Context
  shell:
    chdir: /tmp/devops/eksctl
    cmd: make set_context

- name: Get microservice env
  shell:
    chdir: /tmp/devops/kubernetes/eks
    cmd: aws s3api get-object --bucket {{s3_bucket}} --key env/.microservice.env  .env

- name: Install services
  shell:
    chdir: /tmp/devops/kubernetes/eks
    cmd: make init
