apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "dw-microservice-secrets"
        objectType: "secretsmanager"
        jmesPath:
          - path: DB_USERNAME
            objectAlias: DB_USERNAME
          - path: DB_PASSWORD
            objectAlias: DB_PASSWORD
          - path: DB_HOST
            objectAlias: DB_HOST
          - path: DB_PORT
            objectAlias: DB_PORT
          - path: DB_NAME
            objectAlias: DB_NAME
          - path: ENCRYPT_SECRET_KEY
            objectAlias: ENCRYPT_SECRET_KEY
          - path: JWT_SECRET_KEY
            objectAlias: JWT_SECRET_KEY
  secretObjects:
    - secretName: microservice-secrets
      type: Opaque
      data:
        - objectName: DB_USERNAME
          key: DB_USERNAME
        - objectName: DB_PASSWORD
          key: DB_PASSWORD
        - objectName: DB_HOST
          key: DB_HOST
        - objectName: DB_PORT
          key: DB_PORT
        - objectName: DB_NAME
          key: DB_NAME
        - objectName: ENCRYPT_SECRET_KEY
          key: ENCRYPT_SECRET_KEY
        - objectName: JWT_SECRET_KEY
          key: JWT_SECRET_KEY
