apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: v1
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: zorin
      http:
        paths:
          - path: /banks
            pathType: Prefix
            backend:
              service:
                name: bank-service-v1
                port:
                  number: 8083

          - path: /branches
            pathType: Prefix
            backend:
              service:
                name: bank-service-v1
                port:
                  number: 8083

          - path: /login
            pathType: Prefix
            backend:
              service:
                name: user-service-v1
                port:
                  number: 8070

          - path: /users
            pathType: Prefix
            backend:
              service:
                name: user-service-v1
                port:
                  number: 8070

          - path: /applicants
            pathType: Prefix
            backend:
              service:
                name: underwriter-service-v1
                port:
                  number: 8071

          - path: /applications
            pathType: Prefix
            backend:
              service:
                name: underwriter-service-v1
                port:
                  number: 8071

          - path: /transactions
            pathType: Prefix
            backend:
              service:
                name: transaction-service-v1
                port:
                  number: 8073
