apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-microservice-deployment
  labels:
    app: user-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-microservice
  template:
    metadata:
      labels:
        app: user-microservice
    spec:
      containers:
        - name: user-microservice
          image: captainsalt/user-microservice
          resources:
            limits:
              memory: 2.5G
              cpu: "1.5"
          ports:
            - containerPort: 8070
          env:
            - name: APP_PORT
              value: "8070"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: database-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: database-password
            - name: ENCRYPT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: encrypt-secret-key
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: jwt-secret-key
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: database-host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: database-port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: database-name
---
apiVersion: v1
kind: Service
metadata:
  name: user-microservice
spec:
  type: NodePort
  selector:
    app: user-microservice
  ports:
    - port: 8070
      targetPort: 8070
      nodePort: 30000
