apiVersion: apps/v1
kind: Deployment

metadata:
  name: bank-deployment
  namespace: microservice
  labels:
    app: bank-microservice
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: bank-microservice
  template:
    metadata:
      labels:
        app: bank-microservice
    spec:
      containers:
        - name: bank-microservice
          image: 862167864120.dkr.ecr.us-east-1.amazonaws.com/dw-bank-microservice
          resources:
            limits:
              cpu: "2"
              memory: "4G"
          ports:
            - containerPort: 8083
          env:
            - name: APP_PORT
              value: "8083"
          envFrom:
            - configMapRef:
                name: eks-config
                optional: false
---
apiVersion: v1
kind: Service
metadata:
  name: bank-service
  namespace: microservice
  labels:
    app: bank-microservice
spec:
  type: NodePort
  selector:
    app: bank-microservice
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30001
