apiVersion: apps/v1
kind: Deployment

metadata:
  name: transaction-deployment
  namespace: microservice
  labels:
    app: transaction-microservice
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: transaction-microservice
  template:
    metadata:
      labels:
        app: transaction-microservice
    spec:
      containers:
        - name: transaction-microservice
          image: 862167864120.dkr.ecr.us-east-1.amazonaws.com/dw-transaction-microservice
          resources:
            limits:
              cpu: "2"
              memory: "4G"
          ports:
            - containerPort: 8073
          env:
            - name: APP_PORT
              value: "8073"
          envFrom:
            - configMapRef:
                name: eks-config
                optional: false
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: microservice
  labels:
    app: transaction-microservice
spec:
  type: NodePort
  selector:
    app: transaction-microservice
  ports:
    - protocol: TCP
      port: 8073
      targetPort: 8073
      nodePort: 30003
