apiVersion: apps/v1
kind: Deployment

metadata:
  name: user-deployment
  namespace: microservice
  labels:
    app: user-microservice
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: user-microservice
  template:
    metadata:
      labels:
        app: user-microservice
    spec:
      containers:
        - name: user-microservice
          image: 862167864120.dkr.ecr.us-east-1.amazonaws.com/dw-user-microservice
          resources:
            limits:
              cpu: "2"
              memory: "4G"
          ports:
            - containerPort: 8070
          env:
            - name: APP_PORT
              value: "8070"
          envFrom:
            - configMapRef:
                name: eks-config
                optional: false
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: microservice
  labels:
    app: user-microservice
spec:
  type: NodePort
  selector:
    app: user-microservice
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
      nodePort: 30000
