version: "3.7"

volumes:
  aline-mysql-data:

networks:
  default:

services:
  aline-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: aline-db
    expose:
      - 3306
    env_file:
      - .env
    volumes:
      - ./init-sql:/docker-entrypoint-initdb.d:ro
      - aline-mysql-data:/var/lib/mysql
    cap_add:
      - SYS_NICE

  adminer:
    image: adminer
    container_name: aline-adminer
    ports:
      - 9000:8080
    depends_on:
      - aline-db

  user:
    image: captainsalt/user-microservice
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - APP_PORT=8070
    ports:
      - 8070:8070
    depends_on:
      - aline-db

  bank:
    image: captainsalt/bank-microservice
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - APP_PORT=8083
    ports:
      - 8083:8083
    depends_on:
      - aline-db

  transaction:
    image: captainsalt/transaction-microservice
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - APP_PORT=8073
    ports:
      - 8073:8073
    depends_on:
      - aline-db

  underwriter:
    image: captainsalt/underwriter-microservice
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - APP_PORT=8071
    ports:
      - 8071:8071
    depends_on:
      - aline-db
