- name: Get EC2 Elastic instance
  hosts: localhost
  tasks:
    - name: Register instance
      ec2_instance_info:
        region: us-east-1
        filters:
          "tag:Name": "DW Elastic"
          "instance-state-name": "running"
          "key-name": "dw-us-east-1"
      register: elastic

    - name: Add instances to elastic group
      add_host:
        hostname: "{{ item.public_ip_address }}"
        groupname: elastic
      loop: "{{ elastic.instances }}"

    - name: Download pem key
      aws_s3:
        bucket: dw-infra-bucket
        object: /keys/dw-us-east-1.pem
        dest: ../files/dw-us-east-1.pem
        mode: get
        overwrite: different

    - name: Change pem permissons
      shell: chmod 400 ../files/dw-us-east-1.pem
