version: "3.7"

volumes:
  artifactory:
  artifactory-jcr:

  certs:
  vhost:
  html:
  acme:

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy.conf:/etc/nginx/proxy.conf
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    restart: always
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    volumes_from:
      - nginx-proxy

  artifactory-jcr:
    image: ${DOCKER_REGISTRY}/jfrog/artifactory-jcr:${ARTIFACTORY_VERSION}
    container_name: artifactory
    restart: always
    depends_on:
      - nginx-proxy
      - nginx-proxy-acme
    environment:
      - JF_ROUTER_ENTRYPOINTS_EXTERNALPORT=${JF_ROUTER_ENTRYPOINTS_EXTERNALPORT}
      - VIRTUAL_HOST=dw.jcr.cloudsharks.name,art.localhost
      - VIRTUAL_PORT=${JF_ROUTER_ENTRYPOINTS_EXTERNALPORT}
      - LETSENCRYPT_HOST=dw.jcr.cloudsharks.name
    volumes:
      - artifactory:/var/opt/jfrog/artifactory
      - /etc/localtime:/etc/localtime:ro
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000

  artifactory:
    image: ${DOCKER_REGISTRY}/jfrog/artifactory-oss:${ARTIFACTORY_VERSION}
    container_name: jcr-artifactory
    restart: always
    depends_on:
      - nginx-proxy
      - nginx-proxy-acme
    environment:
      - JF_ROUTER_ENTRYPOINTS_EXTERNALPORT=${JF_ROUTER_ENTRYPOINTS_EXTERNALPORT}
      - VIRTUAL_HOST=dw.artifactory.cloudsharks.name,jcr.localhost
      - VIRTUAL_PORT=${JF_ROUTER_ENTRYPOINTS_EXTERNALPORT}
      - LETSENCRYPT_HOST=dw.artifactory.cloudsharks.name
    volumes:
      - artifactory-jcr:/var/opt/jfrog/artifactory
      - /etc/localtime:/etc/localtime:ro
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
