branch: main
git_repo: "{{vault_git_repo}}"
s3_bucket: "{{vault_s3_bucket}}"

aws_environment:
  AWS_ACCESS_KEY_ID: "{{aws_key}}"
  AWS_SECRET_ACCESS_KEY: "{{aws_secret}}"
  AWS_DEFAULT_REGION: "{{aws_region}}"
