- name: Install pip
  apt:
    update_cache: yes
    pkg: python3-pip

- name: Install boto3
  shell: pip install boto3

- name: Register {{ artifactory_record }} to route 53
  environment: "{{ aws_environment }}"
  community.aws.route53:
    state: present
    overwrite: true
    zone: "{{ hosted_zone }}"
    record: "{{ artifactory_record }}"
    type: A
    ttl: 600
    value: "{{ groups['artifactory'] | join(',') }}"
    wait: yes

- name: Register {{ jcr_record }} to route 53
  environment: "{{ aws_environment }}"
  community.aws.route53:
    state: present
    overwrite: true
    zone: "{{ hosted_zone }}"
    record: "{{ jcr_record }}"
    type: A
    ttl: 600
    value: "{{ groups['artifactory'] | join(',') }}"
    wait: yes
