apiVersion: apps/v1
kind: Deployment
metadata:
  name: underwriter-microservice-deployment
  labels:
    app: underwriter-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: underwriter-microservice
  template:
    metadata:
      labels:
        app: underwriter-microservice
    spec:
      containers:
        - name: underwriter-microservice
          image: captainsalt/underwriter-microservice
          resources:
            limits:
              memory: 2.5G
              cpu: "1.5"
          ports:
            - containerPort: 8071
          env:
            - name: APP_PORT
              value: "8071"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: database-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: database-password
            - name: ENCRYPT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: encrypt-secret-key
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: jwt-secret-key
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: database-host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: database-port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: database-name
---
apiVersion: v1
kind: Service
metadata:
  name: underwriter-microservice
spec:
  type: NodePort
  selector:
    app: underwriter-microservice
  ports:
    - port: 8071
      targetPort: 8071
      nodePort: 30003
