---
- name: Get EC2 Bastion instance
  hosts: localhost
  remote_user: root

  tasks:
    - name: Register instance
      amazon.aws.ec2_instance_info:
        filters:
          "tag:Name": "DW Bastion"
          "instance-state-name": "running"
          "key-name": "dw-us-east-1"
      register: bastion

    - name: Add instances to bastion group
      add_host:
        hostname: "{{ item.public_ip_address }}"
        groupname: bastion
      loop: "{{ bastion.instances }}"

- name: Configure instance(s)
  hosts: bastion
  become: yes
  remote_user: ubuntu
  vars:
    ansible_ssh_private_key_file: ./dw-us-east-1.pem
  tasks:
    - name: Update apt repo
      command: sudo apt update

    - name: Update packages
      command: sudo apt upgrade -y

    - name: Install mysql client
      command: sudo apt install -y mysql-client-core-8.0
