- import_playbook: tasks/register-instance.yml
  vars:
    tagName: "DW Elastic"
    groupNames:
      - aws-vars
      - elastic

- name: Initialize elastic server
  hosts: elastic
  remote_user: ubuntu
  become: yes
  roles:
    - elastic-stack
