- import_playbook: tasks/register-elastic-stack.yml

- name: Initialize elastic server
  hosts: elastic
  roles:
    - elastic-stack
  remote_user: ubuntu
  become: yes
  vars_files:
    - vars/aws/vars.yml
