- import_playbook: tasks/register-bastion.yml

- name: Initialize bastion server
  hosts: bastion
  roles:
    - bastion
  remote_user: ubuntu
  become: yes
  vars:
    user_name: ubuntu
    ansible_ssh_private_key_file: ./files/dw-us-east-1.pem
