- import_playbook: tasks/register-instance.yml
  vars:
    tagName: "DW Artifactory"
    groupNames:
      - artifactory

- name: Init
  hosts: artifactory
  remote_user: ubuntu
  become: yes
  roles:
    - qol-config
    - artifactory

- name: Register route53 records for artifactory
  hosts: localhost
  tasks:
    - community.aws.route53:
        state: present
        overwrite: true
        zone: cloudsharks.name
        record: dw.artifactory.cloudsharks.name
        type: A
        ttl: 600
        value: "{{ groups['artifactory'] | join(',') }}"
        wait: yes

    - community.aws.route53:
        state: present
        overwrite: true
        zone: cloudsharks.name
        record: dw.jcr.cloudsharks.name
        type: A
        ttl: 600
        value: "{{ groups['artifactory'] | join(',') }}"
        wait: yes
