- import_playbook: tasks/register-instance.yml
  vars:
    tagName: "DW Artifactory"
    groupNames:
      - aws-vars
      - artifactory

- name: Init artifactory
  hosts: artifactory
  remote_user: ubuntu
  become: yes
  roles:
    - qol-config
    - artifactory
