- import_playbook: tasks/register-elastic-stack.yml

- name: Initialize elastic server
  hosts: elastic
  roles:
    - elastic-stack
  remote_user: ubuntu
  become: yes
  vars:
    ansible_ssh_private_key_file: ./files/dw-us-east-1.pem
