- name: Install elastic stack
  shell: |
    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
    sudo apt-get install -y apt-transport-https
    echo "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main" | sudo tee /etc/apt/sources.list.d/elastic-8.x.list
    sudo apt-get update
    sudo apt-get install -y elasticsearch kibana logstash filebeat

- name: Turn off elasticsearch SSL
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: "xpack.security.enabled:\\s+true"
    line: "xpack.security.enabled: false"
    backrefs: yes
    firstmatch: yes

- name: Change kibana server host
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: ".*server.host:.*"
    line: 'server.host: "0.0.0.0"'
    backrefs: yes
    firstmatch: yes

- name: Start elastic search
  ansible.builtin.systemd:
    name: elasticsearch
    state: started

- name: Start kibana
  ansible.builtin.systemd:
    name: kibana
    state: started
