- name: Install aws cli
  shell: |
    sudo apt install -y unzip
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install

- name: Configure aws cli
  ansible.builtin.expect:
    command: aws configure --profile filebeat
    responses:
      "AWS Access Key ID.*": "{{aws_key}}"
      "AWS Secret Access Key.*": "{{aws_secret}}"
      "Default region name.*": "{{aws_region}}"
      "Default output format": None

- name: Install elastic stack
  shell: |
    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
    sudo apt-get install -y apt-transport-https
    echo "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main" | sudo tee /etc/apt/sources.list.d/elastic-8.x.list
    sudo apt-get update
    sudo apt-get install -y elasticsearch kibana filebeat

- name: Turn off elasticsearch SSL
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: "xpack.security.enabled:\\s+true"
    line: "xpack.security.enabled: false"
    backrefs: yes
    firstmatch: yes

- name: Change kibana server host
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: ".*server.host:.*"
    line: 'server.host: "0.0.0.0"'
    backrefs: yes
    firstmatch: yes

- name: Start elastic search
  ansible.builtin.systemd:
    name: elasticsearch
    state: started

- name: Start kibana
  ansible.builtin.systemd:
    name: kibana
    state: started

- name: Configure aws filebeat module
  copy:
    backup: true
    remote_src: true
    dest: /etc/filebeat/modules.d/aws.yml
    content: |
      - module: aws
        cloudwatch:
          enabled: true
          var.queue_url: https://sqs.us-east-1.amazonaws.com/862167864120/test-queue
          var.credential_profile_name: filebeat

- name: Enable AWS filebeat module
  command: filebeat modules enable aws

- name: Start filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: started
