apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ required ".Values.serviceName" .Values.serviceName }}-deployment
  namespace: {{ required ".Values.namespace" .Values.namespace }}
  labels:
    app: {{ required ".Values.serviceName" .Values.serviceName }}-microservice
spec:
  replicas: {{ required ".Values.replicas" .Values.replicas }}
  strategy:
    type: {{ .Values.strategy.type }}
  selector:
    matchLabels:
      app: {{ required ".Values.serviceName" .Values.serviceName }}-microservice
  template:
    metadata:
      labels:
        app: {{ required ".Values.serviceName" .Values.serviceName }}-microservice
    spec:
      serviceAccount: microservice
      containers:
        - name: {{ required ".Values.serviceName" .Values.serviceName }}-microservice
          image: {{ required ".Values.aws.ecrRepository" .Values.aws.ecrRepository }}/dw-{{ required ".Values.serviceName" .Values.serviceName }}-microservice:{{ required ".Values.image.tag" .Values.image.tag }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: {{ required ".Values.ports.exposedPort" .Values.ports.exposedPort }}
          env:
            - name: APP_PORT
              value: {{ required ".Values.ports.exposedPort" .Values.ports.exposedPort | quote }}
          envFrom:
            - secretRef:
                name: microservice-secrets
          volumeMounts:
            - name: secrets-volume
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-volume
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: aws-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: {{ required ".Values.serviceName" .Values.serviceName }}-service
  namespace: {{ required ".Values.namespace" .Values.namespace }}
  labels:
    app: {{ required ".Values.serviceName" .Values.serviceName }}-microservice
spec:
  type: NodePort
  selector:
    app: {{ required ".Values.serviceName" .Values.serviceName }}-microservice
  ports:
    - protocol: TCP
      port: {{ required ".Values.ports.exposedPort" .Values.ports.exposedPort }}
      targetPort: {{ required ".Values.ports.exposedPort" .Values.ports.exposedPort }}
      nodePort: {{ required ".Values.ports.nodePort" .Values.ports.nodePort }}
