{{- define "microservice.labels" }}
app: {{ required ".Values.serviceName" .Values.serviceName }}-microservice
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ required ".Values.serviceName" .Values.serviceName }}-microservice
  namespace: {{ required ".Values.namespace" .Values.namespace }}
  labels:
    {{- include "microservice.labels" . | indent 4 }}
spec:
  replicas: {{ required ".Values.replicas" .Values.replicas }}
  strategy:
    type: {{ .Values.strategy.type }}
  selector:
    matchLabels:
      {{- include "microservice.labels" . | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "microservice.labels" . | indent 8 }}
    spec:
      containers:
        - name: {{ required ".Values.serviceName" .Values.serviceName }}-microservice
          image: {{ required ".Values.repository" .Values.repository }}/dw-{{ required ".Values.serviceName" .Values.serviceName }}-microservice:{{ required ".Values.image.tag" .Values.image.tag }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: {{ required ".Values.ports.appPort" .Values.ports.appPort }}
          env:
            - name: APP_PORT
              value: {{ required ".Values.ports.appPort" .Values.ports.appPort | quote }}
          envFrom:
            - secretRef:
                name: microservice-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: {{ required ".Values.serviceName" .Values.serviceName }}-service
  namespace: {{ required ".Values.namespace" .Values.namespace }}
  labels:
    {{- include "microservice.labels" . | indent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "microservice.labels" . | indent 4 }}
  ports:
    - protocol: TCP
      port: {{ required ".Values.ports.appPort" .Values.ports.appPort }}
      targetPort: {{ required ".Values.ports.appPort" .Values.ports.appPort }}
      nodePort: {{ required ".Values.ports.nodePort" .Values.ports.nodePort }}